# Apple Fruit Quality Classification using SVM

Build an SVM classifier that predicts whether an apple is **good** or **bad** quality based on its physical properties.

---

**Tasks:**

1. **Load:** Load the training and test datasets.
2. **Preprocess:** Separate features and target, encode labels, scale features.
3. **Train:** Train an SVM classifier on the training data.
4. **Predict:** Predict the quality of apples in the test data and store in `svm_predictions`.

---

**Expected Variable:**


Store your test predictions in a variable named exactly **`svm_predictions`**.

In [1]:
# Run this cell before writing your solution

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score

train_df = pd.read_csv('https://s3.ap-south-1.amazonaws.com/new-assets.ccbp.in/frontend/content/aiml/classical-ml/apple_train.csv')
test_df = pd.read_csv('https://s3.ap-south-1.amazonaws.com/new-assets.ccbp.in/frontend/content/aiml/classical-ml/apple_test.csv')

print(f'Train: {train_df.shape}')
print(f'Test: {test_df.shape}')
train_df.head()

Train: (3200, 8)
Test: (800, 7)

,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
0,-1.011533,2.308289,1.705463,3.094887,1.411367,-5.199663,2.621552,good
1,-0.930772,-1.130286,1.215035,-0.592831,-1.575231,0.259948,-1.200660,bad
2,-1.622328,2.266139,-0.260213,0.881820,1.834090,-1.351047,2.706358,bad
3,1.831696,-1.400384,-2.133087,-0.467853,1.395362,0.614227,0.586655,good
4,-2.076145,-0.275632,-1.066856,3.079851,-2.318860,-1.946524,-1.115163,bad

In [2]:
train_df.head()

,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
0,-1.011533,2.308289,1.705463,3.094887,1.411367,-5.199663,2.621552,good
1,-0.930772,-1.130286,1.215035,-0.592831,-1.575231,0.259948,-1.200660,bad
2,-1.622328,2.266139,-0.260213,0.881820,1.834090,-1.351047,2.706358,bad
3,1.831696,-1.400384,-2.133087,-0.467853,1.395362,0.614227,0.586655,good
4,-2.076145,-0.275632,-1.066856,3.079851,-2.318860,-1.946524,-1.115163,bad

In [3]:
!pip install -U scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/site-packages (1.9.1)
Requirement already satisfied: numpy>=1.24.1 in /usr/local/lib/python3.11/site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.11/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in /usr/local/lib/python3.11/site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in /usr/local/lib/python3.11/site-packages (from scikit-learn) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /usr/local/lib/python3.11/site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.11/site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
train_df.columns

Index(['Size', 'Weight', 'Sweetness', 'Crunchiness', 'Juiciness', 'Ripeness',
       'Acidity', 'Quality'],
      dtype='str')

In [6]:
X = train_df.drop('Quality',axis=1)
y = train_df['Quality']

In [8]:
lb = LabelEncoder()
y_enc = lb.fit_transform(y)

In [10]:
y_enc

array([1, 0, 0, ..., 1, 1, 1], shape=(3200,))

In [11]:
from sklearn.svm import SVC

In [13]:
svc = SVC()
svc.fit(X,y_enc)

SVC()

In [14]:
svc.score(X,y_enc)

0.90125

In [15]:
svm_predictions = svc.predict(test_df)
print(svm_predictions)

[1 1 0 1 1 1 0 1 0 1 0 0 0 0 0 1 1 0 1 0 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 0 0 0 1 0 0 0 0 0 1 1 1 1 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 0 0 1 1 1 0 1 0 0 1 1 1 1 0 0 0 0 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 0
 1 0 1 0 0 1 1 0 0 1 0 1 1 0 1 1 0 0 1 0 1 1 0 0 0 1 0 1 1 0 0 0 1 1 0 1 1
 0 1 0 0 0 1 0 1 1 1 1 1 1 1 0 1 0 0 1 0 0 0 0 0 1 1 0 1 0 0 1 0 0 1 0 0 0
 1 1 1 0 1 1 0 1 1 0 1 0 0 1 0 1 1 0 0 1 1 0 1 1 1 0 1 1 1 0 1 0 0 1 0 1 1
 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 0 0 1 0 0 1 0 0 1 0 1
 0 1 1 1 0 1 0 0 1 1 1 0 0 1 1 0 1 0 1 0 1 0 1 0 1 1 1 0 0 1 0 0 0 1 1 1 0
 1 1 0 1 1 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1
 1 0 0 1 0 1 0 1 1 0 0 1 0 1 0 0 1 0 1 1 0 1 0 1 1 1 1 0 1 1 1 0 1 1 1 1 1
 1 0 1 0 1 0 1 0 1 1 0 0 1 1 1 0 0 0 1 1 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 1 0
 1 1 0 1 1 1 0 0 1 1 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 1 1 0 0 0 0 1 1 0 0 0 0
 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1 0 0 1 1 0 0 1 1 1 0 1 0 0 1 1 1 0 0 0 0
 0 1 1 0 1 1 0 0 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 0 1 1 1 0 0 1 0 1 0 1
 0 1 0 0 0 1 1 0 1 1 1 1 0 0 0 0 1 1 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 1 1 1 1
 0 0 1 1 1 0 1 1 0 0 1 1 0 0 1 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 1 1 0
 1 0 0 1 0 1 0 0 0 1 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1 1 0 1 0 0 0 1 1 1 0 1 1
 1 0 1 0 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 1 0 0 1 0 1 0 1 1 1 0 1 1 1
 1 1 1 1 1 0 1 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 1 0 1 1 0 0 0 0 1 0 1 0
 1 0 0 0 1 0 1 1 1 0 1 0 0 0 0 0 1 1 0 0 0 1 0 1 1 0 1 1 0 0 1 1 1 1 1 0 1
 1 0 0 0 1 0 1 0 1 1 1 1 0 1 0 1 1 0 0 1 0 0 1 0 0 1 1 1 1 0 1 0 0 0 0 0 0
 1 0 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 0 0 1]